Bash script that will display information about subdomains

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,34 +1,36 @@
 #!/usr/bin/env bash
+# Script to report information about server subdomains
 
-# Function to display information about a subdomain
-display_info() {
-    subdomain="$1"
-    domain="$2"
-    result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
-    record_type=$(echo "$result" | awk '{print $4}')
-    destination=$(echo "$result" | awk '{print $5}')
+check_domain() {
+  local domain="$1"
+  local subdomain="$2"
+  local subdomains=("www" "lb-01" "web-01" "web-02")
+
+  # Validate input
+  if [ -z "$domain" ]; then
+    echo "Error: Domain name not provided."
+    exit 1
+  fi
+
+  if [ -z "$subdomain" ]; then
+    # No subdomain specified, do all
+    for sub in "${subdomains[@]}"; do
+      query_domain="$sub.$domain"
+      result=$(dig "$query_domain" +short)
+      record_type=$(dig "$query_domain" +short | awk '{print $2}')
+      destination=$(dig "$query_domain" +short)
+
+      echo "The subdomain $sub is a $record_type record and points to $destination"
+    done
+  else
+    # Subdomain specified
+    query_domain="$subdomain.$domain"
+    result=$(dig "$query_domain" +short)
+    record_type=$(dig "$query_domain" +short | awk '{print $2}')
+    destination=$(dig "$query_domain" +short)
+
     echo "The subdomain $subdomain is a $record_type record and points to $destination"
+  fi
 }
 
-# Define your server information
-web_server_01_ip="54.87.234.24"
-web_server_02_ip="18.235.243.195"
-load_balancer_ip="35.153.93.22"
-
-# Main script
-if [ $# -eq 1 ]; then
-    # If only the domain is provided, display information for all subdomains
-    domain="$1"
-    subdomains=("www" "lb-01" "web-01" "web-02")
-    for subdomain in "${subdomains[@]}"; do
-        display_info "$subdomain" "$domain"
-    done
-elif [ $# -eq 2 ]; then
-    # If both domain and subdomain are provided, display information for the specified subdomain
-    subdomain="$2"
-    domain="$1"
-    display_info "$subdomain" "$domain"
-else
-    echo "Usage: $0 <domain> [subdomain]"
-    exit 1
-fi
+check_domain "$1" "$2"
